#!/bin/bash


## basic setup

source consts
sudo apt-get install `cat requirements`

sudo virtualenv $ENV_PATH
sudo chown -R $USER:$USER $ENV_PATH
echo "alias trailsenv='source $ENV_PATH/bin/activate'" >> ~/.bashrc
source ~/.bashrc
trailsenv
pip install -r requirements.pip


## GIS support for postgres

sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main" >> /etc/apt/sources.list'
wget --quiet -O - http://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc | sudo apt-key add -
sudo apt-get update
sudo apt-get install postgresql-9.3 postgresql-9.3-postgis pgadmin3 postgresql-contrib

